### ISSUE TITLE
英文封面的标题设置了首行缩进

### ISSUE THREAD

**Issue by SamTripleOne** [ixzhao/BUAA_Dissertation_Template#2]
![2023-03-16](https://user-images.githubusercontent.com/62505930/225560810-9bf9e6f3-7f40-4b95-a4fc-cf2a8382480b.png)
如图，虽然规定的模板里英文标题也是缩进了1.28cm，但是中文标题就是完全居中，这里缩进一下真的合理吗

**Comment by ixzhao** [comment]
可能是当时从《规定》里复制封面到模板的时候疏忽了，不过影响不大，《规定》里几个英文标题的缩进设置也是不统一的。
《规定》里对此没有特殊要求，只要最终纸质效果是居中的就好。
