### ISSUE TITLE
Microsoft Office 365中，修改题注的宏失效

### ISSUE THREAD

**Issue by SamTripleOne** [ixzhao/BUAA_Dissertation_Template#3]
环境是Microsoft 365 企业应用版 (O365ProPlusRetail)，确认已经启用所有宏
插入图表题注时，点击引用-插入题注无法实现自动修改题注格式
录屏如下👇
https://user-images.githubusercontent.com/62505930/227567285-0a3068cc-4565-4ad2-afaa-c0c4a3a2eecf.mp4

**Comment by ixzhao** [comment]
"自动修改题注格式“的前提是运行AddCaption这个宏，在运行这个宏的基础上，可以实现题注格式的自动修改。
至于其他实现方式，欢迎PR。

**Comment by SamTripleOne** [comment]
问题已解决，按Alt+F8，编辑AddCaption这个宏，定位到这一行
![1](https://user-images.githubusercontent.com/62505930/227678291-d90699e1-2261-4de8-97c1-286cf7a4d7e7.png)
修改代码如下即可（将AddCaption替换为InsertCaption）
![2](https://user-images.githubusercontent.com/62505930/227678178-d674e396-5142-42e4-8dda-9b16d7e30e3b.png)
[原贴](https://blog.sina.com.cn/s/blog_51817ae50102w8mz.html)中使用的代码，注释说明适配的是Word2003-2013，更改后在最新的Microsoft 365中也可以实现[以前怎么插题注现在还怎么用，零学习成本与多余步骤](https://blog.sina.com.cn/s/blog_51817ae50102w8mz.html#:~:text=1.%C2%A0%E7%A8%8B%E5%BA%8F%E6%98%AF%E8%B0%83%E7%94%A8%E7%B3%BB%E7%BB%9F%E7%9A%84%E2%80%9C%E6%8F%92%E5%85%A5%E9%A2%98%E6%B3%A8%E5%AF%B9%E8%AF%9D%E6%A1%86%E2%80%9D%EF%BC%8C%E4%BB%A5%E5%89%8D%E6%80%8E%E4%B9%88%E6%8F%92%E9%A2%98%E6%B3%A8%E7%8E%B0%E5%9C%A8%E8%BF%98%E6%80%8E%E4%B9%88%E7%94%A8%EF%BC%8C%E9%9B%B6%E5%AD%A6%E4%B9%A0%E6%88%90%E6%9C%AC%E4%B8%8E%E5%A4%9A%E4%BD%99%E6%AD%A5%E9%AA%A4)的效果

**Comment by ixzhao** [comment]
修改了，感谢提醒。
